# Generated by Django 2.1.5 on 2019-07-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ask_for_perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pronum', models.IntegerField(default=0, max_length=10, null=True)),
                ('type', models.IntegerField(max_length=1)),
                ('order', models.IntegerField(max_length=10)),
            ],
            options={
                'verbose_name': '请求',
                'verbose_name_plural': '请求',
            },
        ),
        migrations.CreateModel(
            name='business',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('usernum', models.IntegerField(max_length=6)),
                ('pronum', models.IntegerField(max_length=6)),
                ('dateon', models.DateTimeField(max_length=10)),
                ('dateoff', models.DateTimeField(max_length=10)),
                ('accept', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '出差记录',
                'verbose_name_plural': '出差记录',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='dailycheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernum', models.IntegerField(max_length=6)),
                ('pronum', models.IntegerField(max_length=6)),
                ('date', models.DateTimeField(max_length=20)),
                ('timeon', models.TimeField(max_length=10)),
                ('timeoff', models.TimeField(max_length=10)),
                ('late', models.BooleanField(default=1)),
                ('leave', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': '上班记录',
                'verbose_name_plural': '上班记录',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='dayoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronum', models.IntegerField(default=0, max_length=10, null=True)),
                ('date', models.CharField(max_length=10, verbose_name='休息日期')),
            ],
            options={
                'verbose_name': '休息日',
                'verbose_name_plural': '休息日',
            },
        ),
        migrations.CreateModel(
            name='dayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronum', models.IntegerField(default=0, max_length=10, null=True)),
                ('date', models.CharField(max_length=10, verbose_name='休息日期')),
            ],
            options={
                'verbose_name': '加班',
                'verbose_name_plural': '加班',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('usernum', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('IMEI', models.CharField(max_length=16, unique=True)),
                ('telenum', models.IntegerField(max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('sex', models.BooleanField(choices=[(0, '男'), (1, '女')], max_length=1, null=True)),
                ('position', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('pronum', models.IntegerField(default=0, max_length=10, null=True)),
                ('home', models.CharField(max_length=100, null=True, verbose_name='家庭住址')),
                ('age', models.IntegerField(max_length=2, null=True, verbose_name='年龄')),
                ('department', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernum', models.IntegerField(max_length=6)),
                ('pronum', models.IntegerField(max_length=6)),
                ('date', models.DateTimeField(max_length=20)),
                ('timeoff', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '加班记录',
                'verbose_name_plural': '加班记录',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('pronum', models.IntegerField(max_length=6)),
                ('usernum', models.IntegerField(max_length=6)),
                ('date', models.CharField(max_length=10, verbose_name='请假日期时间')),
                ('accept', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '请假记录',
                'verbose_name_plural': '请假记录',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronum', models.IntegerField(max_length=20, unique=True)),
                ('usernum', models.IntegerField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('timeon', models.CharField(max_length=10)),
                ('timeoff', models.CharField(max_length=10)),
                ('ps', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=20, null=True, verbose_name='公司名')),
                ('notice', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['pronum'],
            },
        ),
        migrations.CreateModel(
            name='Reg_mesg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_email', models.CharField(max_length=30, unique=True)),
                ('r_vcode', models.CharField(max_length=5)),
                ('r_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '注册',
                'verbose_name_plural': '注册',
                'ordering': ['r_email'],
            },
        ),
        migrations.CreateModel(
            name='user_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=8)),
                ('use_token', models.CharField(max_length=100, null=True)),
                ('user_last_time', models.DateTimeField(max_length=20, null=True)),
            ],
        ),
    ]
